/**
 * Supported AI providers
 */
export type AIProviderType = 'gemini' | 'groq' | 'ollama';

/**
 * Gemini AI configuration
 */
export interface GeminiConfig {
  apiKey: string;
  model?: 'gemini-2.5-flash' | 'gemini-2.5-pro' | 'gemini-1.5-pro' | 'gemini-1.5-flash' | 'gemini-pro';
}



/**
 * Groq AI configuration
 */
export interface GroqConfig {
  apiKey: string;
  model?: 'llama-3.3-70b-versatile' | 'llama-3.1-70b-versatile' | 'llama-3.1-8b-instant' | 'mixtral-8x7b-32768' | 'gemma2-9b-it';
}

/**
 * Configuration interface for the Layr extension
 */
export interface LayrConfig {
  // Legacy support
  geminiApiKey?: string;

  // Multi-provider configuration
  aiProvider?: AIProviderType;
  gemini?: GeminiConfig;
  groq?: GroqConfig;
}

/**
 * Represents a project plan generated by the AI or rule-based system
 */
export interface ProjectPlan {
  title: string;
  overview: string;
  requirements: string[];
  fileStructure: FileStructureItem[];
  nextSteps: PlanStep[];
  generatedAt: Date;
  generatedBy: 'ai' | 'rules';
}

/**
 * Represents a file or directory in the project structure
 */
export interface FileStructureItem {
  name: string;
  type: 'file' | 'directory';
  path: string;
  description?: string;
  children?: FileStructureItem[];
}

/**
 * Represents a step in the project plan
 */
export interface PlanStep {
  id: string;
  description: string;
  completed: boolean;
  priority: 'high' | 'medium' | 'low';
  estimatedTime?: string;
  dependencies?: string[];
}

/**
 * Interface for AI providers
 */
export interface AIProvider {
  readonly name: string;
  readonly type: AIProviderType;

  generatePlan(prompt: string, options?: { planSize?: string, planType?: string }): Promise<string>;
  refineSection(sectionContent: string, refinementPrompt: string, fullContext: string): Promise<string>;
  validateApiKey(apiKey: string): Promise<boolean>;
  getSupportedModels(): string[];
  isAvailable(): Promise<boolean>;
}

/**
 * Interface for plan generators (AI or rule-based)
 */
export interface PlanGenerator {
  generatePlan(prompt: string): Promise<ProjectPlan>;
  isAvailable(): Promise<boolean>;
}

/**
 * AI provider factory interface
 */
export interface AIProviderFactory {
  createProvider(type: AIProviderType, config: { apiKey?: string, model?: string, customBaseUrl?: string, modelName?: string }): AIProvider;
  getSupportedProviders(): AIProviderType[];
}

/**
 * Template for rule-based plan generation
 */
export interface PlanTemplate {
  keywords: string[];
  title: string;
  overview: string;
  requirements: string[];
  fileStructure: FileStructureItem[];
  nextSteps: PlanStep[];
}
