/**
 * Supported AI providers
 */
export type AIProviderType = 'gemini' | 'groq' | 'ollama';

/**
 * Gemini AI configuration
 */
export interface GeminiConfig {
  apiKey: string;
  model?: 'gemini-2.5-flash' | 'gemini-2.5-pro' | 'gemini-1.5-pro' | 'gemini-1.5-flash' | 'gemini-pro';
}



/**
 * Groq AI configuration
 */
export interface GroqConfig {
  apiKey: string;
  model?: 'llama-3.3-70b-versatile' | 'llama-3.1-70b-versatile' | 'llama-3.1-8b-instant' | 'mixtral-8x7b-32768' | 'gemma2-9b-it';
}

/**
 * Configuration interface for the Layr extension
 */
export interface LayrConfig {
  // Legacy support
  geminiApiKey?: string;

  // Multi-provider configuration
  aiProvider?: AIProviderType;
  gemini?: GeminiConfig;
  groq?: GroqConfig;
}

/**
 * Represents a project plan generated by the AI or rule-based system
 */
export interface ProjectPlan {
  title: string;
  overview: string;
  requirements: string[];
  fileStructure: FileStructureItem[];
  nextSteps: PlanStep[];
  generatedAt: Date;
  generatedBy: 'ai' | 'rules';
}

/**
 * Represents a file or directory in the project structure
 */
export interface FileStructureItem {
  name: string;
  type: 'file' | 'directory';
  path: string;
  description?: string;
  children?: FileStructureItem[];
}

/**
 * Represents a step in the project plan
 */
export interface PlanStep {
  id: string;
  description: string;
  completed: boolean;
  priority: 'high' | 'medium' | 'low';
  estimatedTime?: string;
  dependencies?: string[];
}

/**
 * Interface for AI providers
 */
export interface AIProvider {
  readonly name: string;
  readonly type: AIProviderType;

  generatePlan(prompt: string, options?: { planSize?: string, planType?: string }): Promise<string>;
  refineSection(sectionContent: string, refinementPrompt: string, fullContext: string): Promise<string>;
  validateApiKey(apiKey: string): Promise<boolean>;
  getSupportedModels(): string[];
  isAvailable(): Promise<boolean>;
}

/**
 * Interface for plan generators (AI or rule-based)
 */
export interface PlanGenerator {
  generatePlan(prompt: string): Promise<ProjectPlan>;
  isAvailable(): Promise<boolean>;
}

/**
 * AI provider factory interface
 */
export interface AIProviderFactory {
  createProvider(type: AIProviderType, config: { apiKey?: string, model?: string, customBaseUrl?: string, modelName?: string }): AIProvider;
  getSupportedProviders(): AIProviderType[];
}

/**
 * Template for rule-based plan generation
 */
export interface PlanTemplate {
  keywords: string[];
  title: string;
  overview: string;
  requirements: string[];
  fileStructure: FileStructureItem[];
  nextSteps: PlanStep[];
}

/**
 * Error types for plan generation
 */
export class PlanGenerationError extends Error {
  constructor(message: string, public cause?: Error) {
    super(message);
    this.name = 'PlanGenerationError';
  }
}

export class APIKeyMissingError extends PlanGenerationError {
  constructor(_provider?: AIProviderType) {
    const message = `AI provider is not configured or unavailable.

How to fix:
1. Verify your configuration in VS Code Settings or .env file
2. Check your internet connection
3. Ensure you have the necessary API credentials
4. Reload the window (Ctrl+R) to apply changes

For detailed setup instructions:
- Visit: https://github.com/manasdutta04/layr#setup
- Check documentation: https://github.com/manasdutta04/layr`;

    super(message);
    this.name = 'APIKeyMissingError';
  }
}

export class UnsupportedProviderError extends PlanGenerationError {
  constructor(provider: string) {
    const message = `Unsupported AI provider: "${provider}".

Supported providers: gemini, groq

Both providers work seamlessly:
- Gemini: Requires API key setup (https://ai.google.dev)
- Groq: Works via secure proxy (zero setup needed)

Setup guide: https://github.com/manasdutta04/layr#setup`;

    super(message);
    this.name = 'UnsupportedProviderError';
  }
}

export class AIServiceError extends PlanGenerationError {
  constructor(message: string, cause?: Error) {
    const fullMessage = `AI service error: ${message}

Troubleshooting steps:
1. Check your internet connection
2. Verify your configuration settings
3. Ensure you have sufficient quota or credits
4. Try again with a simpler project description
5. Wait a few moments and retry

If the issue persists:
- Review your configuration: https://github.com/manasdutta04/layr#setup
- Report the issue: https://github.com/manasdutta04/layr/issues
- Check documentation for troubleshooting: https://github.com/manasdutta04/layr#troubleshooting`;

    super(fullMessage, cause);
    this.name = 'AIServiceError';
  }
}