/**
 * Supported AI providers
 */
export type AIProviderType = 'gemini' | 'groq';

/**
 * Gemini AI configuration
 */
export interface GeminiConfig {
  apiKey: string;
  model?: 'gemini-2.5-flash' | 'gemini-2.5-pro' | 'gemini-1.5-pro' | 'gemini-1.5-flash' | 'gemini-pro';
}

/**
 * Groq AI configuration
 */
export interface GroqConfig {
  apiKey: string;
  model?: 'llama-3.3-70b-versatile' | 'llama-3.1-70b-versatile' | 'llama-3.1-8b-instant' | 'mixtral-8x7b-32768' | 'gemma2-9b-it';
}

/**
 * Configuration interface for the Layr extension
 */
export interface LayrConfig {
  // Legacy support
  geminiApiKey?: string;
  
  // Multi-provider configuration
  aiProvider?: AIProviderType;
  gemini?: GeminiConfig;
  groq?: GroqConfig;
}

/**
 * Represents a project plan generated by the AI or rule-based system
 */
export interface ProjectPlan {
  title: string;
  overview: string;
  requirements: string[];
  fileStructure: FileStructureItem[];
  nextSteps: PlanStep[];
  generatedAt: Date;
  generatedBy: 'ai' | 'rules';
}

/**
 * Represents a file or directory in the project structure
 */
export interface FileStructureItem {
  name: string;
  type: 'file' | 'directory';
  path: string;
  description?: string;
  children?: FileStructureItem[];
}

/**
 * Represents a step in the project plan
 */
export interface PlanStep {
  id: string;
  description: string;
  completed: boolean;
  priority: 'high' | 'medium' | 'low';
  estimatedTime?: string;
  dependencies?: string[];
}

/**
 * Interface for AI providers
 */
export interface AIProvider {
  readonly name: string;
  readonly type: AIProviderType;
  
  generatePlan(prompt: string, options?: any): Promise<string>;
  validateApiKey(apiKey: string): Promise<boolean>;
  getSupportedModels(): string[];
  isAvailable(): Promise<boolean>;
}

/**
 * Interface for plan generators (AI or rule-based)
 */
export interface PlanGenerator {
  generatePlan(prompt: string): Promise<ProjectPlan>;
  isAvailable(): Promise<boolean>;
}

/**
 * AI provider factory interface
 */
export interface AIProviderFactory {
  createProvider(type: AIProviderType, config: any): AIProvider;
  getSupportedProviders(): AIProviderType[];
}

/**
 * Template for rule-based plan generation
 */
export interface PlanTemplate {
  keywords: string[];
  title: string;
  overview: string;
  requirements: string[];
  fileStructure: FileStructureItem[];
  nextSteps: PlanStep[];
}

/**
 * Error types for plan generation
 */
export class PlanGenerationError extends Error {
  constructor(message: string, public cause?: Error) {
    super(message);
    this.name = 'PlanGenerationError';
  }
}

export class APIKeyMissingError extends PlanGenerationError {
  constructor(provider?: AIProviderType) {
    let message = '';
    
    if (provider === 'gemini') {
      message = `Gemini API key is missing or invalid. 

How to fix:
1. Get your Gemini API key from: https://ai.google.dev/tutorials/rest_quickstart
2. Set it in VS Code Settings (Ctrl+,) under layr.geminiApiKey or create a .env file
3. Reload the window (Ctrl+R) to apply changes

Need help? Visit: https://github.com/manasdutta04/layr#setup`;
    } else if (provider === 'groq') {
      message = `Groq provider is temporarily unavailable. 

Groq works through a secure backend proxy - no API key configuration needed from you!
If you see this error, the backend service may be down.

Troubleshooting:
1. Check your internet connection
2. Try again in a few moments
3. Report at: https://github.com/manasdutta04/layr/issues`;
    } else {
      message = `AI provider is not configured. 

Please set up an AI provider (Gemini or Groq):

For Gemini:
1. Get API key from: https://ai.google.dev/tutorials/rest_quickstart
2. Add to VS Code Settings or .env file

For Groq:
- Works via secure proxy (no setup needed)

Setup guide: https://github.com/manasdutta04/layr#setup`;
    }
    
    super(message);
    this.name = 'APIKeyMissingError';
  }
}

export class UnsupportedProviderError extends PlanGenerationError {
  constructor(provider: string) {
    const message = `Unsupported AI provider: "${provider}".

Supported providers: gemini, groq

Both providers work seamlessly:
- Gemini: Requires API key setup (https://ai.google.dev)
- Groq: Works via secure proxy (zero setup needed)

Setup guide: https://github.com/manasdutta04/layr#setup`;
    
    super(message);
    this.name = 'UnsupportedProviderError';
  }
}

export class AIServiceError extends PlanGenerationError {
  constructor(message: string, cause?: Error) {
    const fullMessage = `AI service error: ${message}

Troubleshooting steps:
1. Check your internet connection
2. Ensure sufficient quota/credits if using Gemini
3. Try with a simpler project description
4. Wait a few seconds and try again

Common issues:
- Gemini: Verify API key is valid - https://ai.google.dev
- Groq: Backend proxy may be temporarily down

For more help:
- Visit: https://github.com/manasdutta04/layr/issues
- Check API status at: https://ai.google.dev or https://status.groq.com`;
    
    super(fullMessage, cause);
    this.name = 'AIServiceError';
  }
}