import { describe, it, expect } from 'vitest';
import { Planner } from '../../src/planner';
import { MockAIProvider } from '../mocks/providers';

describe('Planner Markdown', () => {
  it('prepends watermark when overview contains markdown and no watermark', async () => {
    const markdown = '# Title\nContent';
    const planner = new Planner(new MockAIProvider(markdown));
    const plan = await planner.generatePlan('test');
    const formatted = planner.planToMarkdown(plan);
    expect(formatted).toContain('*Generated by Layr on');
    expect(formatted).toContain('# Title');
  });

  it('keeps existing watermark', async () => {
    const markdown = '*Generated by Layr on X*\n\n---\n\n# Title';
    const planner = new Planner(new MockAIProvider(markdown));
    const plan = await planner.generatePlan('test');
    const formatted = planner.planToMarkdown(plan);
    expect(formatted.startsWith('*Generated by Layr')).toBe(true);
  });

  it('formats rule-based plan structure when not AI markdown', () => {
    const p = new Planner(new MockAIProvider('# M'));
    const customPlan = {
      title: 'T',
      overview: 'O',
      requirements: ['R1', 'R2'],
      fileStructure: [],
      nextSteps: [],
      generatedAt: new Date(),
      generatedBy: 'rules' as const
    };
    const formatted = p.planToMarkdown(customPlan);
    expect(formatted).toContain('# T');
    expect(formatted).toContain('## Requirements');
    expect(formatted).toContain('- R1');
  });
});
